# Generated by Django 5.0.4 on 2024-05-12 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('npm', models.IntegerField(unique=True)),
                ('kelas', models.CharField(choices=[('A', 'Kelas A'), ('B', 'Kelas B'), ('C', 'Kelas C'), ('D', 'Kelas D')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelajaran', models.CharField(max_length=255)),
                ('jam_mulai', models.CharField(max_length=255)),
                ('jam_selesai', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=255)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='api.guru')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('hadir', models.BooleanField(default=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='api.guru')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='api.siswa')),
            ],
        ),
    ]
